on: [push, pull_request]

name: tests

jobs:
  test-lockfile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tc: [1.70.0, stable, nightly]
    steps:
    - uses: taiki-e/checkout-action@v1
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack,cargo-minimal-versions
    - run: rustup set profile minimal
    - run: rustup toolchain install ${{ matrix.tc }}
    - run: cargo +${{ matrix.tc }} test --all --all-features
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tc: [1.70.0, stable, beta]
    steps:
    - uses: taiki-e/checkout-action@v1
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack,cargo-minimal-versions
    - run: rustup set profile minimal
    - run: rustup toolchain install ${{ matrix.tc }}
    - run: cargo +${{ matrix.tc }} minimal-versions test --all --all-features
  cross-compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [1.70.0, stable, beta]
        cc:
        - aarch64-linux-android
        - i686-pc-windows-gnu
        - i686-unknown-freebsd
        - i686-unknown-linux-gnu
        - wasm32-unknown-unknown
        - x86_64-apple-darwin
        - x86_64-unknown-redox
    steps:
    - uses: taiki-e/checkout-action@v1
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack,cargo-minimal-versions
    - run: rustup set profile minimal
    - run: rustup toolchain install ${{ matrix.tc }}
    - run: rustup target add ${{ matrix.cc }}
    - run: cargo +${{ matrix.tc }} minimal-versions build --all --all-features --target=${{ matrix.cc }}
  cross-compile-ios:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        tc: [1.70.0, stable, beta]
        cc: [aarch64-apple-ios]
    steps:
    - uses: taiki-e/checkout-action@v1
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack,cargo-minimal-versions
    - run: rustup set profile minimal
    - run: rustup toolchain install ${{ matrix.tc }}
    - run: rustup target add ${{ matrix.cc }}
    - run: cargo +${{ matrix.tc }} minimal-versions build --all --all-features --target=${{ matrix.cc }}
